app:
  base-url: ${APP_BASE_URL}

spring:
  datasource:
    url: jdbc:mysql://db:3306/moodlog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  web:
    resources:
      static-locations: classpath:/static/

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
          google:
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          naver:
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}

claude:
  api:
    key: ${CLAUDE_API_KEY}

upload:
  path: /app/uploads

logging:
  level:
    root: WARN
    com.example.moodlog: INFO
